/* =====================================================================
   chapitres/cm1/_flash.js -- Questions flash prêtes des chapitres du CM1 et du CM2.

   Demandé : « des petites questions déjà préparées utilisables par l'enseignant avec les
   flashcodes sur chaque thème des cours ». Les chapitres du CE2 déclarent les leurs dans
   cm1Chapitre({ flash }) ; ceux du CM1 et du CM2, écrits avant, les ont ici, rangés par niveau et
   titre exact du chapitre (CHCM1 / CHCM2 dans app.js). Format : { q, r: [2 à 4 réponses, A à D],
   ok: index de la bonne, l: numéro de la leçon du cours (choix « Partie du cours ») }. Lu par flash-prets.js (bouton « Questions flash (cartes) »).
   Règles du cours moyen respectées : ni tableau de conversion, ni rapporteur, ni produit en croix.
   ===================================================================== */
(() => {
const F = {
  // ------------------------------------------------------------- CM1
  // l : numéro de la leçon du cours sur laquelle porte la question (choix « Partie du cours »).
  "cm1|Nombres entiers jusqu'à 9 999": [
    { l: 1, q: "1 millier = …", r: ["10 centaines", "100 centaines", "10 dizaines", "1 000 centaines"], ok: 0 },
    { l: 1, q: "Combien de chiffres faut-il pour écrire 3 058 ?", r: ["3", "4", "5", "58"], ok: 1 },
    { l: 1, q: "« Deux mille six » s'écrit…", r: ["2 600", "2 006", "2 060", "206"], ok: 1 },
    { l: 2, q: "5 000 + 300 + 7 = …", r: ["5 307", "5 370", "537", "53 007"], ok: 0 },
    { l: 2, q: "4 m + 2 c + 9 u = …", r: ["429", "4 209", "4 290", "4 029"], ok: 1 },
    { l: 2, q: "6 803 = 6 000 + 800 + …", r: ["30", "3", "300", "0"], ok: 1 },
    { l: 3, q: "Dans 4 572, quel est le chiffre des centaines ?", r: ["4", "5", "7", "2"], ok: 1 },
    { l: 3, q: "Combien de dizaines dans 3 460 ?", r: ["6", "46", "346", "3 460"], ok: 2 },
    { l: 3, q: "Combien de centaines dans 2 780 ?", r: ["7", "27", "278", "2"], ok: 1 },
    { l: 4, q: "Demi-droite graduée de 100 en 100 : le point est juste après 2 900. Il vaut…", r: ["2 910", "3 000", "2 901", "3 900"], ok: 1 },
    { l: 4, q: "À mi-chemin entre 4 000 et 5 000, on lit…", r: ["4 050", "4 500", "4 005", "4 100"], ok: 1 },
    { l: 5, q: "Quel nombre est le plus grand ?", r: ["8 909", "9 089", "8 990", "9 008"], ok: 1 },
    { l: 5, q: "Quel nombre vient juste après 6 999 ?", r: ["6 990", "7 000", "7 999", "6 998"], ok: 1 },
    { l: 5, q: "Entre quels milliers se trouve 7 405 ?", r: ["6 000 et 7 000", "7 000 et 8 000", "7 400 et 7 500", "8 000 et 9 000"], ok: 1 },
    { l: 6, q: "Du plus petit au plus grand, lequel vient en premier : 3 210 ; 3 120 ; 3 201 ; 3 012 ?", r: ["3 210", "3 120", "3 201", "3 012"], ok: 3 },
    { l: 6, q: "Rangés du plus grand au plus petit, quel est le dernier : 1 999 ; 2 001 ; 1 909 ; 2 010 ?", r: ["1 999", "2 001", "1 909", "2 010"], ok: 2 },
  ],
  "cm1|Fractions": [
    { l: 1, q: "Une pizza partagée en 4 parts égales : chaque part est…", r: ["un quart", "un demi", "un tiers", "quatre"], ok: 0 },
    { l: 1, q: "Pour avoir des tiers, on partage l'unité en…", r: ["2 parts égales", "3 parts égales", "3 parts quelconques", "4 parts égales"], ok: 1 },
    { l: 2, q: "Dans 3/8, le numérateur est…", r: ["3", "8", "11", "5"], ok: 0 },
    { l: 2, q: "« Trois dixièmes » s'écrit…", r: ["3/10", "10/3", "3/100", "1/3"], ok: 0 },
    { l: 2, q: "5/6 se lit…", r: ["cinq sixièmes", "six cinquièmes", "cinq sur six unités", "cinquante-six"], ok: 0 },
    { l: 3, q: "Combien de quarts dans une unité ?", r: ["2", "4", "1", "10"], ok: 1 },
    { l: 3, q: "Quelle fraction est plus grande que 1 ?", r: ["3/4", "5/5", "7/4", "1/2"], ok: 2 },
    { l: 3, q: "7/4 = 1 + …", r: ["3/4", "7/4", "1/4", "4/4"], ok: 0 },
    { l: 3, q: "6/6 est égal à…", r: ["0", "1", "6", "36"], ok: 1 },
    { l: 4, q: "Entre quels entiers se trouve 9/4 ?", r: ["0 et 1", "1 et 2", "2 et 3", "9 et 10"], ok: 2 },
    { l: 4, q: "Unité partagée en 5 : le point est à la 3e graduation après 0. Il vaut…", r: ["3/5", "5/3", "1/3", "3"], ok: 0 },
    { l: 4, q: "Sur la demi-droite, 1/2 est…", r: ["avant 0", "entre 0 et 1", "entre 1 et 2", "après 2"], ok: 1 },
    { l: 5, q: "Le quart de 20 €, c'est…", r: ["4 €", "5 €", "10 €", "80 €"], ok: 1 },
    { l: 5, q: "La moitié de 18 billes, c'est…", r: ["6", "9", "36", "8"], ok: 1 },
    { l: 5, q: "Le tiers de 12, c'est…", r: ["3", "4", "6", "36"], ok: 1 },
  ],
  "cm1|Droites parallèles et perpendiculaires": [
    { l: 1, q: "Deux droites perpendiculaires forment…", r: ["un angle droit", "aucun angle", "un angle aigu", "un angle obtus"], ok: 0 },
    { l: 1, q: "Pour vérifier que deux droites sont perpendiculaires, on utilise…", r: ["le compas", "l'équerre", "la gomme", "le crayon"], ok: 1 },
    { l: 1, q: "Deux bords voisins d'une feuille sont…", r: ["parallèles", "perpendiculaires", "confondus", "courbes"], ok: 1 },
    { l: 1, q: "Le petit carré dessiné à l'intersection de deux droites indique…", r: ["un angle droit", "des droites parallèles", "le milieu", "une erreur"], ok: 0 },
    { l: 1, q: "Deux droites perpendiculaires forment combien d'angles droits ?", r: ["1", "2", "3", "4"], ok: 3 },
    { l: 2, q: "Deux droites parallèles…", r: ["se coupent", "ne se coupent jamais", "forment un angle droit", "sont toujours verticales"], ok: 1 },
    { l: 2, q: "Les bords opposés d'une feuille sont…", r: ["parallèles", "perpendiculaires", "en biais", "courbes"], ok: 0 },
    { l: 2, q: "Deux droites perpendiculaires à une même droite sont…", r: ["parallèles entre elles", "perpendiculaires entre elles", "confondues", "courbes"], ok: 0 },
    { l: 2, q: "Entre deux droites parallèles, l'écart…", r: ["reste toujours le même", "grandit", "diminue", "est nul"], ok: 0 },
    { l: 2, q: "Deux droites qui se coupent sont…", r: ["parallèles", "sécantes", "toujours perpendiculaires", "confondues"], ok: 1 },
  ],
  "cm1|Opérations sur les nombres entiers": [
    { l: 1, q: "Le résultat d'une addition s'appelle…", r: ["la somme", "la différence", "le produit", "le quotient"], ok: 0 },
    { l: 1, q: "Le résultat d'une multiplication s'appelle…", r: ["la somme", "la différence", "le produit", "le reste"], ok: 2 },
    { l: 1, q: "Le résultat d'une soustraction s'appelle…", r: ["la somme", "la différence", "le produit", "le quotient"], ok: 1 },
    { l: 2, q: "356 + 478 = …", r: ["724", "834", "824", "734"], ok: 1 },
    { l: 2, q: "1 275 + 425 = …", r: ["1 600", "1 700", "1 690", "1 650"], ok: 1 },
    { l: 3, q: "1 000 − 365 = …", r: ["635", "735", "645", "765"], ok: 0 },
    { l: 3, q: "502 − 38 = …", r: ["464", "474", "536", "540"], ok: 0 },
    { l: 4, q: "23 × 4 = …", r: ["82", "92", "27", "96"], ok: 1 },
    { l: 4, q: "125 × 3 = …", r: ["365", "375", "128", "325"], ok: 1 },
    { l: 5, q: "Dans la division de 37 par 5 : 37 = 5 × 7 + 2. Le reste est…", r: ["5", "7", "2", "37"], ok: 2 },
    { l: 5, q: "72 ÷ 8 = …", r: ["8", "9", "7", "64"], ok: 1 },
    { l: 5, q: "Dans une division, le reste est toujours…", r: ["plus petit que le diviseur", "plus grand que le diviseur", "égal au quotient", "zéro"], ok: 0 },
    { l: 6, q: "Quel nombre est un multiple de 6 ?", r: ["16", "26", "36", "46"], ok: 2 },
    { l: 6, q: "Quel nombre est un diviseur de 20 ?", r: ["3", "4", "6", "8"], ok: 1 },
    { l: 7, q: "Quel nombre est divisible par 5 ?", r: ["143", "250", "322", "71"], ok: 1 },
    { l: 7, q: "Quel nombre est divisible par 2 ?", r: ["357", "481", "614", "999"], ok: 2 },
    { l: 7, q: "Un nombre divisible par 10 se termine par…", r: ["0", "5", "1", "2"], ok: 0 },
  ],
  "cm1|Longueurs, masses, contenances": [
    { l: 1, q: "Pour mesurer un segment, on place sur une extrémité…", r: ["le 0 de la règle", "le 1 de la règle", "le bout de la règle", "le milieu de la règle"], ok: 0 },
    { l: 1, q: "Un segment mesure 6 cm 3 mm, c'est-à-dire…", r: ["63 mm", "603 mm", "9 mm", "6,3 mm"], ok: 0 },
    { l: 2, q: "1 m = …", r: ["10 cm", "100 cm", "1 000 cm", "1 cm"], ok: 1 },
    { l: 2, q: "3 km = …", r: ["300 m", "3 000 m", "30 m", "30 000 m"], ok: 1 },
    { l: 2, q: "Dans « millimètre », « milli » veut dire…", r: ["mille fois plus grand", "mille fois plus petit", "cent fois plus petit", "dix fois plus petit"], ok: 1 },
    { l: 2, q: "La hauteur d'une porte est d'environ…", r: ["2 cm", "2 m", "2 km", "20 m"], ok: 1 },
    { l: 3, q: "2 kg = …", r: ["200 g", "2 000 g", "20 g", "20 000 g"], ok: 1 },
    { l: 3, q: "La masse d'un dictionnaire est d'environ…", r: ["1 g", "1 kg", "1 t", "100 kg"], ok: 1 },
    { l: 3, q: "1 t = …", r: ["100 kg", "1 000 kg", "10 kg", "1 000 g"], ok: 1 },
    { l: 4, q: "1 L = …", r: ["10 cL", "100 cL", "1 000 cL", "1 cL"], ok: 1 },
    { l: 4, q: "La contenance d'une canette est…", r: ["33 mL", "33 cL", "33 L", "3 L"], ok: 1 },
    { l: 4, q: "1 L = … mL", r: ["10", "100", "1 000", "10 000"], ok: 2 },
    { l: 5, q: "2 m 35 cm = …", r: ["235 cm", "2 035 cm", "2 350 cm", "37 cm"], ok: 0 },
    { l: 5, q: "5 000 g = …", r: ["5 kg", "50 kg", "500 kg", "0,5 kg"], ok: 0 },
    { l: 5, q: "Plus lourd : 1 kg 200 g ou 1 050 g ?", r: ["1 kg 200 g", "1 050 g", "les deux pareils", "on ne peut pas savoir"], ok: 0 },
  ],
  "cm1|Nombres décimaux": [
    { l: 1, q: "1 unité = … dixièmes", r: ["10", "100", "1", "1 000"], ok: 0 },
    { l: 1, q: "1 dixième = … centièmes", r: ["10", "100", "1", "1 000"], ok: 0 },
    { l: 1, q: "Une unité partagée en 100 parts égales : chaque part est…", r: ["un dixième", "un centième", "une centaine", "un millième"], ok: 1 },
    { l: 2, q: "25/100 s'écrit…", r: ["2,5", "0,25", "25,100", "0,025"], ok: 1 },
    { l: 2, q: "7/10 s'écrit…", r: ["7,10", "0,7", "0,07", "70"], ok: 1 },
    { l: 2, q: "Dans 3,47, le chiffre des dixièmes est…", r: ["3", "4", "7", "47"], ok: 1 },
    { l: 3, q: "4,3 = 4 + …", r: ["3/10", "3/100", "3", "30/10"], ok: 0 },
    { l: 3, q: "5 + 6/10 + 2/100 = …", r: ["5,62", "5,26", "56,2", "5,602"], ok: 0 },
    { l: 3, q: "Dans 12,08, le chiffre des centièmes est…", r: ["0", "8", "1", "2"], ok: 1 },
    { l: 4, q: "Entre quels entiers se trouve 6,8 ?", r: ["5 et 6", "6 et 7", "7 et 8", "68 et 69"], ok: 1 },
    { l: 4, q: "Graduation de 0,1 en 0,1 : juste après 2,9 vient…", r: ["2,10", "3", "2,91", "3,9"], ok: 1 },
    { l: 5, q: "Quel nombre est le plus grand ?", r: ["2,5", "2,45", "2,09", "2,4"], ok: 0 },
    { l: 5, q: "Quel nombre est le plus petit ?", r: ["0,8", "0,75", "0,9", "0,81"], ok: 1 },
    { l: 5, q: "3,5 est compris entre…", r: ["3,4 et 3,6", "3 et 3,4", "3,6 et 4", "35 et 36"], ok: 0 },
  ],
  "cm1|Construction de figures": [
    { l: 1, q: "Le milieu d'un segment de 8 cm est à … de chaque extrémité.", r: ["2 cm", "4 cm", "8 cm", "16 cm"], ok: 1 },
    { l: 1, q: "Un polygone à 5 côtés est un…", r: ["quadrilatère", "pentagone", "hexagone", "triangle"], ok: 1 },
    { l: 1, q: "Les « coins » d'un polygone s'appellent…", r: ["les côtés", "les sommets", "les milieux", "les diagonales"], ok: 1 },
    { l: 2, q: "Le diamètre d'un cercle de rayon 5 cm mesure…", r: ["5 cm", "10 cm", "2,5 cm", "15 cm"], ok: 1 },
    { l: 2, q: "Pour tracer un cercle, on utilise…", r: ["l'équerre", "le compas", "la règle seule", "la gomme"], ok: 1 },
    { l: 2, q: "Tous les points d'un cercle sont à la même distance…", r: ["du centre", "du diamètre", "de la règle", "du rayon"], ok: 0 },
    { l: 3, q: "Un triangle qui a 3 côtés de même longueur est…", r: ["isocèle", "équilatéral", "rectangle", "quelconque"], ok: 1 },
    { l: 3, q: "Un triangle rectangle a…", r: ["un angle droit", "deux angles droits", "trois côtés égaux", "quatre côtés"], ok: 0 },
    { l: 3, q: "Un triangle isocèle a…", r: ["2 côtés de même longueur", "3 angles droits", "4 côtés", "aucun côté égal"], ok: 0 },
    { l: 4, q: "Un losange a…", r: ["4 angles droits", "4 côtés de même longueur", "3 côtés", "5 sommets"], ok: 1 },
    { l: 4, q: "Un rectangle a…", r: ["4 angles droits", "4 côtés égaux forcément", "3 angles droits", "aucun angle droit"], ok: 0 },
    { l: 4, q: "Un carré, c'est un quadrilatère avec 4 angles droits et…", r: ["4 côtés de même longueur", "2 côtés seulement", "un cercle", "3 côtés égaux"], ok: 0 },
  ],
  "cm1|Fractions (comparaison et opérations)": [
    { l: 1, q: "1/2 = …/10", r: ["2", "5", "10", "1"], ok: 1 },
    { l: 1, q: "3/10 = …/100", r: ["3", "30", "300", "13"], ok: 1 },
    { l: 1, q: "2/4 est égal à…", r: ["1/2", "2/8", "4/2", "1/4"], ok: 0 },
    { l: 2, q: "Quelle fraction est la plus grande ?", r: ["3/7", "5/7", "2/7", "6/7"], ok: 3 },
    { l: 2, q: "8/5 est…", r: ["plus petit que 1", "égal à 1", "plus grand que 1", "égal à 0"], ok: 2 },
    { l: 2, q: "Quelle fraction est la plus petite ?", r: ["1/2", "1/3", "1/4", "1/5"], ok: 3 },
    { l: 3, q: "2/9 + 5/9 = …", r: ["7/18", "7/9", "3/9", "10/9"], ok: 1 },
    { l: 3, q: "7/12 − 4/12 = …", r: ["3/12", "11/12", "3/0", "3/24"], ok: 0 },
    { l: 3, q: "3/5 + 2/5 = …", r: ["5/10", "1", "6/5", "5/25"], ok: 1 },
    { l: 3, q: "1 − 1/4 = …", r: ["3/4", "1/3", "0/4", "4/3"], ok: 0 },
  ],
  "cm1|Organisation et gestion de données": [
    { l: 1, q: "26 élèves, dont 14 garçons. Combien de filles ?", r: ["12", "14", "40", "10"], ok: 0 },
    { l: 1, q: "Effectifs 12, 8 et 15 : le total est…", r: ["25", "35", "30", "45"], ok: 1 },
    { l: 1, q: "Pour compter vite des votes, on peut faire…", r: ["des bâtons groupés par 5", "un cercle", "une frise", "une division"], ok: 0 },
    { l: 2, q: "Un tableau à double entrée range les données selon…", r: ["1 critère", "2 critères", "3 critères", "aucun critère"], ok: 1 },
    { l: 2, q: "Dans un tableau à double entrée, on lit une case à l'intersection…", r: ["d'une ligne et d'une colonne", "de deux lignes", "de deux colonnes", "du titre et du total"], ok: 0 },
    { l: 3, q: "Dans un diagramme en barres, la barre la plus haute montre…", r: ["le plus grand effectif", "le plus petit effectif", "le total", "le titre"], ok: 0 },
    { l: 3, q: "Axe gradué de 10 en 10 : une barre s'arrête à mi-chemin entre 30 et 40. Elle vaut…", r: ["30", "35", "40", "45"], ok: 1 },
    { l: 3, q: "Deux barres de même hauteur montrent…", r: ["le même effectif", "des effectifs différents", "un total", "une erreur"], ok: 0 },
    { l: 4, q: "Lundi 18 °C, mardi 21 °C. De combien la température a-t-elle augmenté ?", r: ["3 °C", "39 °C", "2 °C", "21 °C"], ok: 0 },
    { l: 4, q: "Sur un graphique, quand la courbe descend, la valeur…", r: ["diminue", "augmente", "reste pareille", "double"], ok: 0 },
  ],
  "cm1|Grands nombres jusqu'à 999 999": [
    { l: 1, q: "« Trente mille quatre cents » s'écrit…", r: ["3 400", "30 400", "300 400", "30 040"], ok: 1 },
    { l: 1, q: "Le nombre qui suit 99 999 est…", r: ["100 000", "999 999", "99 990", "10 000"], ok: 0 },
    { l: 1, q: "205 300 se lit…", r: ["deux cent cinq mille trois cents", "vingt mille cinq cent trois", "deux mille cinquante-trois", "deux cent cinquante trois mille"], ok: 0 },
    { l: 2, q: "400 000 + 6 000 + 20 = …", r: ["46 020", "406 020", "400 620", "460 020"], ok: 1 },
    { l: 2, q: "352 000 = 300 000 + 50 000 + …", r: ["200", "2 000", "20 000", "2"], ok: 1 },
    { l: 3, q: "Dans 452 318, le chiffre des milliers est…", r: ["4", "5", "2", "3"], ok: 2 },
    { l: 3, q: "Combien de milliers dans 245 000 ?", r: ["24", "245", "2 450", "45"], ok: 1 },
    { l: 3, q: "Dans 608 451, le chiffre des centaines de mille est…", r: ["6", "0", "8", "4"], ok: 0 },
    { l: 4, q: "Quel nombre est le plus grand ?", r: ["98 999", "100 001", "99 999", "90 999"], ok: 1 },
    { l: 4, q: "Compare : 305 210 … 350 120", r: ["<", ">", "="], ok: 0 },
    { l: 5, q: "Du plus petit au plus grand, lequel vient en premier : 120 300 ; 102 300 ; 123 000 ; 120 030 ?", r: ["120 300", "102 300", "123 000", "120 030"], ok: 1 },
    { l: 5, q: "Rangés du plus grand au plus petit, quel est le premier : 75 000 ; 705 000 ; 570 000 ; 750 000 ?", r: ["75 000", "705 000", "570 000", "750 000"], ok: 3 },
  ],
  "cm1|Opérations sur les nombres décimaux": [
    { l: 1, q: "2,5 + 1,3 = …", r: ["3,8", "3,5", "4,8", "2,8"], ok: 0 },
    { l: 1, q: "4,75 + 0,25 = …", r: ["4,100", "5", "4,95", "5,25"], ok: 1 },
    { l: 1, q: "Pour poser 3,4 + 12,56, on aligne…", r: ["les virgules", "les premiers chiffres", "les derniers chiffres", "rien"], ok: 0 },
    { l: 2, q: "5,6 − 2,4 = …", r: ["3,2", "3,6", "2,2", "8"], ok: 0 },
    { l: 2, q: "10 − 0,5 = …", r: ["9,5", "10,5", "5", "9,05"], ok: 0 },
    { l: 3, q: "1,5 + 1,5 = …", r: ["2,10", "3", "2,5", "3,5"], ok: 1 },
    { l: 3, q: "6,2 + 0,8 = …", r: ["6,10", "7", "6,28", "7,8"], ok: 1 },
    { l: 4, q: "3,4 × 10 = …", r: ["3,40", "34", "340", "0,34"], ok: 1 },
    { l: 4, q: "45 ÷ 10 = …", r: ["450", "4,5", "0,45", "45,10"], ok: 1 },
    { l: 4, q: "0,7 × 10 = …", r: ["0,70", "7", "70", "0,07"], ok: 1 },
    { l: 5, q: "Ordre de grandeur de 19,8 + 30,1 ?", r: ["50", "5", "500", "40"], ok: 0 },
    { l: 5, q: "Ordre de grandeur de 9,9 + 9,8 ?", r: ["2", "20", "200", "10"], ok: 1 },
  ],
  "cm1|Procédures de calcul mental": [
    { l: 1, q: "7 × 8 = …", r: ["54", "56", "63", "48"], ok: 1 },
    { l: 1, q: "Le double de 35, c'est…", r: ["60", "70", "65", "75"], ok: 1 },
    { l: 1, q: "La moitié de 50, c'est…", r: ["20", "25", "100", "30"], ok: 1 },
    { l: 2, q: "47 + 9 = …", r: ["56", "57", "55", "66"], ok: 0 },
    { l: 2, q: "83 − 19 = …", r: ["64", "62", "74", "66"], ok: 0 },
    { l: 2, q: "56 + 21 = …", r: ["76", "77", "78", "87"], ok: 1 },
    { l: 3, q: "14 × 11 = …", r: ["144", "154", "141", "164"], ok: 1 },
    { l: 3, q: "38 + 47 = …", r: ["75", "85", "84", "95"], ok: 1 },
    { l: 4, q: "72 × 100 = …", r: ["720", "7 200", "72 000", "7 020"], ok: 1 },
    { l: 4, q: "35 × 1 000 = …", r: ["3 500", "35 000", "350 000", "35 100"], ok: 1 },
    { l: 5, q: "2,6 × 10 = …", r: ["2,60", "26", "260", "0,26"], ok: 1 },
    { l: 5, q: "8 ÷ 10 = …", r: ["80", "0,8", "0,08", "8,10"], ok: 1 },
    { l: 6, q: "36 × 5 = …", r: ["150", "180", "185", "160"], ok: 1 },
    { l: 6, q: "25 × 4 = …", r: ["50", "90", "100", "125"], ok: 2 },
    { l: 6, q: "15 × 20 = …", r: ["35", "300", "150", "320"], ok: 1 },
  ],
  "cm1|Résolution de problèmes": [
    { l: 1, q: "Avant de calculer, on commence par…", r: ["lire et comprendre la question", "écrire la phrase réponse", "poser une division", "dessiner un cercle"], ok: 0 },
    { l: 1, q: "La phrase réponse doit…", r: ["répondre à la question, avec l'unité", "répéter l'énoncé", "être un calcul", "être une question"], ok: 0 },
    { l: 2, q: "Il y avait 250 € ; on dépense 85 €. Il reste…", r: ["165 €", "175 €", "335 €", "135 €"], ok: 0 },
    { l: 2, q: "Dans un car : 23 filles et 19 garçons. Combien d'enfants ?", r: ["32", "42", "41", "4"], ok: 1 },
    { l: 3, q: "Léa a 35 billes, Tom 12 de plus. Combien Tom en a-t-il ?", r: ["23", "47", "420", "37"], ok: 1 },
    { l: 3, q: "Paul a 40 €, Zoé a 15 € de moins. Combien a Zoé ?", r: ["55 €", "25 €", "35 €", "15 €"], ok: 1 },
    { l: 4, q: "Un livre coûte 12 €. Combien coûtent 5 livres ?", r: ["17 €", "60 €", "50 €", "7 €"], ok: 1 },
    { l: 4, q: "48 élèves en équipes de 6. Combien d'équipes ?", r: ["8", "42", "54", "6"], ok: 0 },
    { l: 4, q: "28 élèves, dont la moitié de filles. Combien de filles ?", r: ["12", "14", "16", "56"], ok: 1 },
    { l: 5, q: "Un ruban de 3 m coupé en 4 morceaux égaux. Chaque morceau mesure…", r: ["75 cm", "4 cm", "1 m", "30 cm"], ok: 0 },
    { l: 5, q: "3 paquets de 6 gâteaux ; on en mange 5. Il en reste…", r: ["13", "14", "18", "23"], ok: 0 },
  ],
  "cm1|Symétrie axiale": [
    { l: 1, q: "Pour vérifier qu'une figure est symétrique, on peut…", r: ["la plier", "la peser", "la colorier", "compter ses sommets"], ok: 0 },
    { l: 1, q: "Quand on plie selon l'axe, les deux moitiés…", r: ["se superposent", "se croisent", "s'écartent", "disparaissent"], ok: 0 },
    { l: 2, q: "Combien d'axes de symétrie a un carré ?", r: ["1", "2", "4", "0"], ok: 2 },
    { l: 2, q: "Combien d'axes de symétrie a un rectangle qui n'est pas un carré ?", r: ["1", "2", "4", "0"], ok: 1 },
    { l: 2, q: "Quelle lettre a un axe de symétrie vertical ?", r: ["A", "F", "G", "R"], ok: 0 },
    { l: 2, q: "Combien d'axes de symétrie a un cercle ?", r: ["1", "2", "4", "une infinité"], ok: 3 },
    { l: 3, q: "Un point à 3 carreaux de l'axe a son symétrique…", r: ["à 3 carreaux, de l'autre côté", "à 6 carreaux, du même côté", "sur l'axe", "à 1 carreau"], ok: 0 },
    { l: 3, q: "Un point situé sur l'axe a pour symétrique…", r: ["lui-même", "un point à 1 carreau", "aucun point", "le point le plus loin"], ok: 0 },
    { l: 3, q: "Un segment de 4 carreaux a pour symétrique un segment de…", r: ["2 carreaux", "4 carreaux", "8 carreaux", "6 carreaux"], ok: 1 },
  ],
  "cm1|Périmètres": [
    { l: 1, q: "Le périmètre, c'est…", r: ["la longueur du contour", "la surface", "le nombre de côtés", "le plus grand côté"], ok: 0 },
    { l: 1, q: "Une fourmi fait le tour d'une figure : la distance parcourue est…", r: ["le périmètre", "l'aire", "le rayon", "la diagonale"], ok: 0 },
    { l: 2, q: "Triangle de côtés 4 cm, 5 cm et 6 cm : périmètre ?", r: ["15 cm", "120 cm", "11 cm", "20 cm"], ok: 0 },
    { l: 2, q: "Avant d'additionner les côtés, ils doivent être…", r: ["dans la même unité", "tous égaux", "rangés", "pairs"], ok: 0 },
    { l: 2, q: "Rectangle de 1 m sur 50 cm : périmètre ?", r: ["3 m", "1 m 50 cm", "51 cm", "2 m"], ok: 0 },
    { l: 3, q: "Périmètre d'un carré de 6 cm de côté ?", r: ["12 cm", "24 cm", "36 cm", "18 cm"], ok: 1 },
    { l: 3, q: "Périmètre d'un rectangle de 5 cm sur 3 cm ?", r: ["8 cm", "15 cm", "16 cm", "30 cm"], ok: 2 },
    { l: 3, q: "Un carré a un périmètre de 32 cm. Son côté mesure…", r: ["4 cm", "8 cm", "16 cm", "28 cm"], ok: 1 },
    { l: 4, q: "Pour comparer deux contours sans mesurer, on reporte les côtés avec…", r: ["un compas", "une équerre", "une gomme", "une loupe"], ok: 0 },
    { l: 4, q: "Un carré de 4 cm et un rectangle de 6 cm sur 2 cm ont…", r: ["le même périmètre", "des périmètres différents", "la même aire", "rien en commun"], ok: 0 },
  ],
  "cm1|Solides": [
    { l: 1, q: "Quel solide peut rouler ?", r: ["le cube", "le cylindre", "la pyramide", "le pavé droit"], ok: 1 },
    { l: 1, q: "Un dé à jouer a la forme…", r: ["d'un cube", "d'une boule", "d'un cône", "d'un cylindre"], ok: 0 },
    { l: 1, q: "Une boîte à chaussures a la forme…", r: ["d'un pavé droit", "d'une pyramide", "d'une boule", "d'un cône"], ok: 0 },
    { l: 2, q: "Combien de faces a un cube ?", r: ["4", "6", "8", "12"], ok: 1 },
    { l: 2, q: "Combien d'arêtes a un pavé droit ?", r: ["6", "8", "12", "10"], ok: 2 },
    { l: 2, q: "Combien de faces a une pyramide à base carrée ?", r: ["5", "4", "6", "8"], ok: 0 },
    { l: 2, q: "Combien de faces a un prisme droit à base triangulaire ?", r: ["3", "5", "6", "9"], ok: 1 },
    { l: 2, q: "Sur un dessin en perspective, les arêtes cachées sont…", r: ["en pointillés", "en rouge", "en gras", "effacées"], ok: 0 },
    { l: 3, q: "Le patron d'un cube est formé de…", r: ["6 carrés", "4 carrés", "6 rectangles quelconques", "8 triangles"], ok: 0 },
    { l: 3, q: "Un patron, c'est…", r: ["une figure à plier pour fabriquer le solide", "le dessin d'une face", "le nom du solide", "une arête"], ok: 0 },
  ],
  "cm1|Aires": [
    { l: 1, q: "L'aire d'une figure mesure…", r: ["sa surface", "son contour", "un côté", "ses sommets"], ok: 0 },
    { l: 1, q: "Pour une pelouse, l'aire correspond…", r: ["au gazon à semer", "à la clôture", "au portail", "à l'allée"], ok: 0 },
    { l: 2, q: "On découpe une figure et on recolle les morceaux autrement. Son aire…", r: ["augmente", "diminue", "ne change pas", "double"], ok: 2 },
    { l: 2, q: "Une figure posée entièrement sur une autre a une aire…", r: ["plus petite", "plus grande", "égale", "nulle"], ok: 0 },
    { l: 3, q: "Un rectangle de 3 lignes de 5 carreaux contient…", r: ["8 carreaux", "15 carreaux", "16 carreaux", "10 carreaux"], ok: 1 },
    { l: 3, q: "Deux demi-carreaux font…", r: ["1 carreau", "2 carreaux", "un quart de carreau", "4 carreaux"], ok: 0 },
    { l: 3, q: "4 carreaux entiers et 2 demi-carreaux : l'aire est…", r: ["5 carreaux", "6 carreaux", "8 carreaux", "4 carreaux"], ok: 0 },
    { l: 4, q: "Un carré de 1 cm de côté a une aire de…", r: ["1 cm", "1 cm²", "4 cm", "4 cm²"], ok: 1 },
    { l: 4, q: "Un rectangle de 4 cm sur 2 cm a une aire de…", r: ["6 cm²", "8 cm²", "12 cm", "8 cm"], ok: 1 },
    { l: 5, q: "Deux figures de même aire ont-elles toujours le même périmètre ?", r: ["Oui", "Non"], ok: 1 },
    { l: 5, q: "Le périmètre se mesure en cm, l'aire en…", r: ["cm", "cm²", "kg", "L"], ok: 1 },
  ],
  "cm1|Proportionnalité": [
    { l: 1, q: "3 cahiers coûtent 6 €. 6 cahiers coûtent…", r: ["9 €", "12 €", "18 €", "3 €"], ok: 1 },
    { l: 1, q: "Une situation de proportionnalité : si on prend 2 fois plus d'objets, on paie…", r: ["2 fois plus", "pareil", "2 € de plus", "la moitié"], ok: 0 },
    { l: 2, q: "2 kg de pommes coûtent 5 €. 10 kg coûtent…", r: ["25 €", "13 €", "50 €", "15 €"], ok: 0 },
    { l: 2, q: "Pour 4 personnes : 200 g de farine. Pour 8 personnes ?", r: ["204 g", "400 g", "800 g", "100 g"], ok: 1 },
    { l: 3, q: "5 billes pèsent 20 g, 3 billes pèsent 12 g. 8 billes pèsent…", r: ["32 g", "24 g", "40 g", "16 g"], ok: 0 },
    { l: 3, q: "2 places coûtent 14 €, 1 place coûte 7 €. 3 places coûtent…", r: ["21 €", "17 €", "28 €", "16 €"], ok: 0 },
    { l: 4, q: "4 stylos coûtent 8 €. Un stylo coûte…", r: ["2 €", "4 €", "32 €", "12 €"], ok: 0 },
    { l: 4, q: "5 cahiers coûtent 10 €. 7 cahiers coûtent…", r: ["12 €", "14 €", "17 €", "70 €"], ok: 1 },
    { l: 5, q: "L'âge et la taille d'un enfant sont-ils proportionnels ?", r: ["Oui", "Non"], ok: 1 },
    { l: 5, q: "Un pain coûte 1 €. Avec une promotion « 3 pour 2 € », le prix est-il proportionnel ?", r: ["Oui", "Non"], ok: 1 },
  ],
  "cm1|Algèbre": [
    { l: 1, q: "2, 5, 8, 11… Le nombre suivant est…", r: ["12", "13", "14", "15"], ok: 2 },
    { l: 1, q: "100, 90, 80, 70… Le nombre suivant est…", r: ["50", "60", "65", "75"], ok: 1 },
    { l: 1, q: "1, 2, 4, 8… Le nombre suivant est…", r: ["10", "12", "16", "9"], ok: 2 },
    { l: 2, q: "Une suite de figures : 3 allumettes, puis 5, puis 7. La suivante en a…", r: ["8", "9", "10", "14"], ok: 1 },
    { l: 2, q: "Étape 1 : 2 carrés ; étape 2 : 4 carrés ; étape 3 : 6 carrés. Étape 4 ?", r: ["7", "8", "10", "12"], ok: 1 },
    { l: 3, q: "15 + ? = 23", r: ["7", "8", "38", "9"], ok: 1 },
    { l: 3, q: "Vrai ou faux : 7 + 5 = 6 + 6", r: ["Vrai", "Faux"], ok: 0 },
    { l: 3, q: "■ × 6 = 42", r: ["6", "7", "8", "36"], ok: 1 },
    { l: 4, q: "Balance en équilibre : 3 cubes d'un côté, 12 g de l'autre. Un cube pèse…", r: ["3 g", "4 g", "9 g", "36 g"], ok: 1 },
    { l: 4, q: "Balance : un sac + 5 g = 20 g. Le sac pèse…", r: ["25 g", "15 g", "4 g", "100 g"], ok: 1 },
    { l: 5, q: "Programme : × 2, puis + 3. Avec 5, on obtient…", r: ["13", "16", "10", "11"], ok: 0 },
    { l: 5, q: "Programme : + 4. On obtient 10. Le nombre de départ était…", r: ["14", "6", "40", "4"], ok: 1 },
  ],
  "cm1|Angles": [
    { l: 1, q: "Le point où se rejoignent les deux côtés d'un angle est…", r: ["le sommet", "le milieu", "le centre", "l'axe"], ok: 0 },
    { l: 1, q: "Un angle est formé par…", r: ["deux côtés issus d'un même point", "un seul segment", "un cercle", "deux points"], ok: 0 },
    { l: 2, q: "On vérifie un angle droit avec…", r: ["le compas", "l'équerre", "la règle graduée seule", "une ficelle"], ok: 1 },
    { l: 2, q: "Combien d'angles droits a un carré ?", r: ["1", "2", "3", "4"], ok: 3 },
    { l: 2, q: "À 3 h, les aiguilles d'une horloge forment un angle…", r: ["aigu", "droit", "obtus", "plat"], ok: 1 },
    { l: 3, q: "Un angle plus petit qu'un angle droit est…", r: ["aigu", "obtus", "plat", "droit"], ok: 0 },
    { l: 3, q: "Un angle plus grand qu'un angle droit (et plus petit qu'un angle plat) est…", r: ["aigu", "obtus", "nul", "droit"], ok: 1 },
    { l: 3, q: "À 1 h, les aiguilles forment un angle…", r: ["aigu", "droit", "obtus", "plat"], ok: 0 },
    { l: 4, q: "Pour comparer deux angles, on peut utiliser…", r: ["un gabarit (papier calque)", "une balance", "un thermomètre", "une gomme"], ok: 0 },
    { l: 4, q: "Si on allonge les côtés d'un angle, l'angle…", r: ["ne change pas", "devient plus grand", "devient plus petit", "devient droit"], ok: 0 },
  ],
  "cm1|Heures et durées": [
    { l: 1, q: "La petite aiguille indique…", r: ["les heures", "les minutes", "les secondes", "les jours"], ok: 0 },
    { l: 1, q: "La grande aiguille est sur le 9 : il est … minutes.", r: ["9", "45", "30", "15"], ok: 1 },
    { l: 1, q: "3 h de l'après-midi s'écrit…", r: ["3 h", "13 h", "15 h", "18 h"], ok: 2 },
    { l: 2, q: "1 h = … min", r: ["100", "60", "24", "30"], ok: 1 },
    { l: 2, q: "1 jour = … h", r: ["12", "24", "60", "100"], ok: 1 },
    { l: 2, q: "1 min = … s", r: ["100", "60", "10", "30"], ok: 1 },
    { l: 2, q: "2 h 15 min = … min", r: ["215", "135", "120", "150"], ok: 1 },
    { l: 3, q: "« Le film dure 1 h 45 min » : c'est…", r: ["un instant", "une durée", "une date", "un horaire"], ok: 1 },
    { l: 3, q: "« La cantine ouvre à 11 h 45 » : c'est…", r: ["un instant", "une durée", "une vitesse", "une longueur"], ok: 0 },
    { l: 4, q: "De 9 h 45 à 10 h 15, il s'écoule…", r: ["30 min", "70 min", "1 h", "15 min"], ok: 0 },
    { l: 4, q: "Un film de 1 h 30 min commence à 20 h 45. Il finit à…", r: ["21 h 15", "22 h 15", "22 h", "21 h 75"], ok: 1 },
    { l: 4, q: "De 8 h 40 jusqu'à l'heure pile, il faut…", r: ["20 min", "40 min", "60 min", "10 min"], ok: 0 },
  ],
  "cm1|Initiation à la pensée informatique": [
    { l: 1, q: "Le robot suit → → ↑. Combien de cases parcourt-il ?", r: ["2", "3", "4", "1"], ok: 1 },
    { l: 1, q: "Après → →, pour revenir au départ, il faut…", r: ["← ←", "→ →", "↑ ↑", "↓"], ok: 0 },
    { l: 1, q: "Le robot suit ↑ ↑ →. Il finit…", r: ["2 cases plus haut et 1 à droite", "1 case plus haut", "3 cases à droite", "au départ"], ok: 0 },
    { l: 2, q: "« Répéter 4 fois : → » revient à…", r: ["→", "→ → → →", "↑ ↑ ↑ ↑", "← ← ← ←"], ok: 1 },
    { l: 2, q: "Pour répéter des instructions, un programme utilise…", r: ["une boucle", "un bug", "une gomme", "un tableau"], ok: 0 },
    { l: 3, q: "Une erreur dans un programme s'appelle…", r: ["un bug", "une boucle", "un robot", "une flèche"], ok: 0 },
    { l: 3, q: "Le robot devait faire 3 pas mais en fait 4 : il faut…", r: ["enlever une flèche", "ajouter une flèche", "tout recommencer", "tourner"], ok: 0 },
    { l: 4, q: "Programme : + 5, puis × 2. Avec 3, on obtient…", r: ["11", "16", "13", "10"], ok: 1 },
    { l: 4, q: "Dans un programme de construction, l'ordre des étapes…", r: ["compte", "ne compte pas", "est au hasard", "n'existe pas"], ok: 0 },
  ],
  "cm1|Probabilités": [
    { l: 1, q: "Lancer un dé, c'est une expérience…", r: ["de hasard", "certaine", "impossible", "de calcul"], ok: 0 },
    { l: 1, q: "À pile ou face, peut-on savoir à l'avance le résultat ?", r: ["Oui", "Non"], ok: 1 },
    { l: 2, q: "Avec un dé à 6 faces, obtenir 7 est…", r: ["certain", "possible", "impossible", "probable"], ok: 2 },
    { l: 2, q: "Avec un dé à 6 faces, obtenir un nombre entre 1 et 6 est…", r: ["certain", "impossible", "peu probable", "une chance sur deux"], ok: 0 },
    { l: 2, q: "À pile ou face, obtenir pile, c'est…", r: ["une chance sur deux", "impossible", "certain", "une chance sur six"], ok: 0 },
    { l: 3, q: "Un sac contient 9 billes rouges et 1 bleue. Tirer une rouge est…", r: ["impossible", "peu probable", "très probable", "certain"], ok: 2 },
    { l: 3, q: "Un sac contient 9 billes rouges et 1 bleue. Tirer la bleue est…", r: ["certain", "peu probable", "impossible", "très probable"], ok: 1 },
    { l: 3, q: "Avec un dé à 6 faces, obtenir un nombre pair, c'est…", r: ["une chance sur deux", "impossible", "certain", "une chance sur six"], ok: 0 },
  ],
  // ------------------------------------------------------------- CM2
  "cm2|Nombres entiers (révisions jusqu'à 999 999)": [
    { q: "Dans 708 215, le chiffre des dizaines de mille est…", r: ["7", "0", "8", "2"], ok: 1 },
    { q: "Combien de centaines dans 52 300 ?", r: ["3", "523", "52", "5 230"], ok: 1 },
    { q: "Quel nombre est le plus petit ?", r: ["100 100", "99 999", "101 000", "100 010"], ok: 1 },
    { q: "« Six cent mille huit » s'écrit…", r: ["600 008", "600 800", "6 008", "608 000"], ok: 0 },
    { q: "Entre quels milliers se trouve 45 678 ?", r: ["45 000 et 46 000", "44 000 et 45 000", "40 000 et 50 000", "456 000 et 457 000"], ok: 0 },
    { q: "Le nombre qui précède 300 000 est…", r: ["299 999", "300 001", "299 000", "290 000"], ok: 0 },
  ],
  "cm2|Fractions": [
    { q: "11/4 = 2 + …", r: ["3/4", "1/4", "11/4", "2/4"], ok: 0 },
    { q: "Entre quels entiers se trouve 17/5 ?", r: ["2 et 3", "3 et 4", "17 et 18", "1 et 2"], ok: 1 },
    { q: "3 + 2/5 = …/5", r: ["5", "15", "17", "32"], ok: 2 },
    { q: "Quelle fraction est égale à 1 ?", r: ["6/6", "1/6", "6/1", "0/6"], ok: 0 },
    { q: "Une demi-heure, c'est … d'heure.", r: ["1/2", "1/4", "1/3", "2/1"], ok: 0 },
    { q: "Sur une demi-droite graduée en quarts, 6/4 est entre…", r: ["0 et 1", "1 et 2", "2 et 3", "6 et 7"], ok: 1 },
  ],
  "cm2|Longueurs, masses, contenances": [
    { q: "3,5 m = … cm", r: ["35", "350", "3 500", "305"], ok: 1 },
    { q: "2 500 g = … kg", r: ["25", "2,5", "250", "0,25"], ok: 1 },
    { q: "1 L = … mL", r: ["10", "100", "1 000", "10 000"], ok: 2 },
    { q: "1 g = … mg", r: ["10", "100", "1 000", "1"], ok: 2 },
    { q: "1,2 km = … m", r: ["12", "120", "1 200", "12 000"], ok: 2 },
    { q: "La hauteur d'une porte est d'environ…", r: ["2 m", "20 m", "2 cm", "2 km"], ok: 0 },
  ],
  "cm2|Droites, segments et cercles": [
    { q: "[AB) désigne…", r: ["le segment [AB]", "la demi-droite d'origine A qui passe par B", "la droite (AB)", "la longueur AB"], ok: 1 },
    { q: "Un cercle de diamètre 12 cm a un rayon de…", r: ["24 cm", "12 cm", "6 cm", "3 cm"], ok: 2 },
    { q: "Tous les points d'un cercle sont…", r: ["à la même distance du centre", "alignés", "sur un diamètre", "à l'extérieur"], ok: 0 },
    { q: "Deux droites perpendiculaires se coupent en formant…", r: ["un angle droit", "un angle aigu", "aucun angle", "un angle obtus"], ok: 0 },
    { q: "A est à 3 cm du centre d'un cercle de rayon 5 cm. A est…", r: ["sur le cercle", "à l'intérieur du disque", "à l'extérieur du disque", "le centre"], ok: 1 },
    { q: "Deux droites parallèles à une même troisième sont…", r: ["parallèles entre elles", "perpendiculaires", "sécantes", "des segments"], ok: 0 },
  ],
  "cm2|Nombres décimaux jusqu'aux millièmes": [
    { q: "Dans 5,382, le chiffre des millièmes est…", r: ["3", "8", "2", "5"], ok: 2 },
    { q: "47/1 000 s'écrit…", r: ["0,47", "0,047", "4,7", "47,1"], ok: 1 },
    { q: "Quel nombre est le plus grand ?", r: ["3,09", "3,1", "3,099", "3,019"], ok: 1 },
    { q: "L'arrondi à l'unité de 7,6 est…", r: ["7", "8", "7,5", "6"], ok: 1 },
    { q: "1 centième = … millièmes", r: ["10", "100", "1", "1 000"], ok: 0 },
    { q: "Quel nombre est entre 2,4 et 2,5 ?", r: ["2,45", "2,54", "2,04", "2,6"], ok: 0 },
  ],
  "cm2|Figures planes": [
    { q: "Un triangle isocèle a…", r: ["2 côtés de même longueur", "3 angles droits", "4 côtés", "aucun côté égal"], ok: 0 },
    { q: "Un trapèze a…", r: ["2 côtés opposés parallèles", "4 angles droits", "3 côtés", "5 sommets"], ok: 0 },
    { q: "Un quadrilatère à 4 côtés égaux et 4 angles droits est…", r: ["un trapèze", "un carré", "un triangle", "un pentagone"], ok: 1 },
    { q: "Un hexagone a … côtés.", r: ["5", "6", "7", "8"], ok: 1 },
    { q: "Un triangle équilatéral a…", r: ["3 côtés de même longueur", "un angle droit", "2 côtés parallèles", "4 sommets"], ok: 0 },
    { q: "Les côtés opposés d'un rectangle sont…", r: ["parallèles et de même longueur", "perpendiculaires", "de longueurs différentes", "courbes"], ok: 0 },
  ],
  "cm2|Addition et soustraction": [
    { q: "4,7 + 2,5 = …", r: ["6,12", "7,2", "6,2", "7,12"], ok: 1 },
    { q: "10 − 3,6 = …", r: ["7,6", "6,4", "7,4", "6,6"], ok: 1 },
    { q: "125 + 3,4 = …", r: ["128,4", "159", "125,34", "128,04"], ok: 0 },
    { q: "(15 − 5) + 3 = …", r: ["7", "13", "23", "10"], ok: 1 },
    { q: "15 − (5 + 3) = …", r: ["13", "7", "23", "17"], ok: 1 },
    { q: "Ordre de grandeur de 298 + 503 ?", r: ["800", "80", "8 000", "700"], ok: 0 },
  ],
  "cm2|Multiplication": [
    { q: "2,35 × 100 = …", r: ["23,5", "235", "2 350", "0,0235"], ok: 1 },
    { q: "30 × 400 = …", r: ["1 200", "12 000", "120 000", "700"], ok: 1 },
    { q: "1,5 × 4 = …", r: ["4,20", "6", "5,4", "60"], ok: 1 },
    { q: "12 × 25 = …", r: ["250", "300", "275", "325"], ok: 1 },
    { q: "Ordre de grandeur de 49 × 21 ?", r: ["100", "1 000", "10 000", "70"], ok: 1 },
    { q: "0,8 × 1 000 = …", r: ["8", "80", "800", "0,800"], ok: 2 },
  ],
  "cm2|Fractions : comparer et calculer": [
    { q: "Quelle est la plus grande : 3/4 ou 5/8 ?", r: ["3/4", "5/8", "elles sont égales", "on ne peut pas savoir"], ok: 0 },
    { q: "1/3 + 1/6 = …", r: ["2/9", "3/6", "2/6", "1/9"], ok: 1 },
    { q: "3 × 2/7 = …", r: ["6/21", "6/7", "5/7", "2/21"], ok: 1 },
    { q: "Un quart de 20 €, c'est…", r: ["4 €", "5 €", "80 €", "16 €"], ok: 1 },
    { q: "1/2 s'écrit aussi…", r: ["0,2", "0,5", "1,2", "2,1"], ok: 1 },
    { q: "3/4 s'écrit aussi…", r: ["0,34", "0,75", "3,4", "0,25"], ok: 1 },
  ],
  "cm2|Grands nombres jusqu'à 999 999 999": [
    { q: "Dans 247 815 360, le chiffre des millions est…", r: ["2", "4", "7", "8"], ok: 2 },
    { q: "« Trois millions deux cent mille » s'écrit…", r: ["3 200 000", "3 000 200", "320 000", "3 002 000"], ok: 0 },
    { q: "Combien de millions dans 45 600 000 ?", r: ["4", "45", "456", "4 560"], ok: 1 },
    { q: "Quel nombre est le plus grand ?", r: ["99 999 999", "100 000 000", "9 999 999", "10 000 000"], ok: 1 },
    { q: "1 million = … milliers", r: ["10", "100", "1 000", "10 000"], ok: 2 },
    { q: "Le nombre qui suit 9 999 999 est…", r: ["10 000 000", "1 000 000", "99 999 999", "10 000 001"], ok: 0 },
  ],
  "cm2|Multiples et diviseurs": [
    { q: "Quel nombre est un multiple de 5 ?", r: ["52", "75", "83", "101"], ok: 1 },
    { q: "Quel nombre est divisible par 2 ?", r: ["37", "45", "68", "91"], ok: 2 },
    { q: "Combien de diviseurs a 12 ?", r: ["4", "5", "6", "3"], ok: 2 },
    { q: "7 est un diviseur de…", r: ["48", "56", "64", "45"], ok: 1 },
    { q: "Un multiple commun à 4 et à 6 :", r: ["10", "12", "18", "8"], ok: 1 },
    { q: "Un nombre qui se termine par 0 est divisible par…", r: ["2, 5 et 10", "3 seulement", "7", "9"], ok: 0 },
  ],
  "cm2|Division": [
    { q: "Division de 47 par 6 : 47 = 6 × 7 + 5. Le quotient est…", r: ["6", "7", "5", "47"], ok: 1 },
    { q: "Division de 47 par 6 : 47 = 6 × 7 + 5. Le reste est…", r: ["6", "7", "5", "1"], ok: 2 },
    { q: "34,5 ÷ 10 = …", r: ["345", "3,45", "0,345", "34,05"], ok: 1 },
    { q: "120 ÷ 4 = …", r: ["30", "40", "24", "480"], ok: 0 },
    { q: "Dans une division par 6, le reste peut-il être 7 ?", r: ["Oui", "Non"], ok: 1 },
    { q: "9 ÷ 2 = …", r: ["4,5", "4", "5", "4,2"], ok: 0 },
  ],
  "cm2|Résolution de problèmes": [
    { q: "Une trottinette coûte 3 fois plus qu'un casque à 45 €. Elle coûte…", r: ["48 €", "135 €", "15 €", "90 €"], ok: 1 },
    { q: "5 tables de 6 places et 3 tables de 4 : combien de places ?", r: ["42", "30", "44", "18"], ok: 0 },
    { q: "100 élèves, des cars de 30 places. Combien de cars ?", r: ["3", "4", "70", "33"], ok: 1 },
    { q: "Un pull à 38,50 € payé avec 50 €. On rend…", r: ["11,50 €", "12,50 €", "11 €", "88,50 €"], ok: 0 },
    { q: "2 entrées et 3 desserts au choix : combien de menus ?", r: ["5", "6", "8", "9"], ok: 1 },
    { q: "Avant de répondre, on vérifie que le résultat est…", r: ["vraisemblable", "pair", "rond", "grand"], ok: 0 },
  ],
  "cm2|Probabilités": [
    { q: "Avec un dé à 6 faces, chances d'obtenir 6 ?", r: ["1 chance sur 6", "1 chance sur 2", "6 chances sur 6", "aucune"], ok: 0 },
    { q: "Avec un dé à 6 faces, chances d'obtenir un nombre pair ?", r: ["1 sur 6", "3 sur 6", "2 sur 6", "6 sur 6"], ok: 1 },
    { q: "Un sac : 3 billes rouges, 5 bleues. Chances de tirer une bleue ?", r: ["5 sur 8", "3 sur 8", "5 sur 3", "1 sur 8"], ok: 0 },
    { q: "Le dé a donné 6 trois fois de suite. Au lancer suivant, le 6 a…", r: ["plus de chances", "moins de chances", "autant de chances", "aucune chance"], ok: 2 },
    { q: "On lance deux fois une pièce. Combien d'issues (PP, PF…) ?", r: ["2", "3", "4", "6"], ok: 2 },
    { q: "Obtenir 0 avec un dé à 6 faces est…", r: ["impossible", "certain", "probable", "une chance sur 6"], ok: 0 },
  ],
  "cm2|Organisation et gestion de données": [
    { q: "Dans un diagramme circulaire, la moitié du disque représente…", r: ["la moitié de l'effectif", "le quart", "le tiers", "tout l'effectif"], ok: 0 },
    { q: "Un quart du disque représente … de l'effectif.", r: ["1/2", "1/4", "1/3", "3/4"], ok: 1 },
    { q: "Températures : 12 °C, 15 °C, 9 °C. La plus basse est…", r: ["12 °C", "15 °C", "9 °C", "36 °C"], ok: 2 },
    { q: "Sur une courbe de température, une montée montre que la température…", r: ["augmente", "baisse", "ne change pas", "disparaît"], ok: 0 },
    { q: "Effectifs 25, 40 et 35 : le total est…", r: ["90", "100", "110", "75"], ok: 1 },
    { q: "Garçons : 132 ; filles : 145. Combien de filles de plus ?", r: ["13", "23", "277", "17"], ok: 0 },
  ],
  "cm2|Programmes de construction": [
    { q: "« Trace le segment [AB] » : on trace…", r: ["le trait qui va de A à B", "une droite sans fin", "un cercle", "une demi-droite"], ok: 0 },
    { q: "Pour tracer une perpendiculaire, on utilise…", r: ["l'équerre", "le compas seul", "la gomme", "un calque"], ok: 0 },
    { q: "Pour reporter une longueur sans la mesurer, on utilise…", r: ["le compas", "l'équerre", "la gomme", "le crayon seul"], ok: 0 },
    { q: "« Trace le cercle de centre O et de rayon 3 cm » : écartement du compas ?", r: ["3 cm", "6 cm", "1,5 cm", "9 cm"], ok: 0 },
    { q: "Dans un programme de construction, l'ordre des étapes…", r: ["est important", "n'a aucune importance", "est alphabétique", "est au hasard"], ok: 0 },
    { q: "« Place I, milieu du segment [AB] », qui mesure 10 cm. Le segment [AI] mesure …", r: ["5 cm", "10 cm", "20 cm", "2 cm"], ok: 0 },
  ],
  "cm2|Symétrie axiale": [
    { q: "Combien d'axes de symétrie a un triangle équilatéral ?", r: ["1", "2", "3", "0"], ok: 2 },
    { q: "Combien d'axes de symétrie a un losange qui n'est pas un carré ?", r: ["1", "2", "4", "0"], ok: 1 },
    { q: "Le symétrique d'un point situé sur l'axe est…", r: ["lui-même", "à 1 carreau", "de l'autre côté", "au hasard"], ok: 0 },
    { q: "Un triangle isocèle (non équilatéral) a combien d'axes ?", r: ["0", "1", "2", "3"], ok: 1 },
    { q: "Par symétrie axiale, les longueurs…", r: ["sont conservées", "doublent", "diminuent", "changent au hasard"], ok: 0 },
    { q: "Axe en diagonale du quadrillage : le symétrique d'une case est…", r: ["sa case « en miroir » par rapport à la diagonale", "toujours la case voisine", "sur la même ligne", "la même case"], ok: 0 },
  ],
  "cm2|Aires": [
    { q: "Aire d'un rectangle de 6 cm sur 4 cm ?", r: ["20 cm²", "24 cm²", "10 cm²", "24 cm"], ok: 1 },
    { q: "Aire d'un carré de 5 cm de côté ?", r: ["20 cm²", "25 cm²", "10 cm²", "25 cm"], ok: 1 },
    { q: "1 dm² = … cm²", r: ["10", "100", "1 000", "20"], ok: 1 },
    { q: "1 m² = … dm²", r: ["10", "100", "1 000", "10 000"], ok: 1 },
    { q: "Carré de 3 cm de côté : périmètre et aire ?", r: ["12 cm et 9 cm²", "9 cm et 12 cm²", "12 cm et 12 cm²", "6 cm et 9 cm²"], ok: 0 },
    { q: "Quelle unité pour l'aire d'une chambre ?", r: ["m²", "cm²", "km", "m"], ok: 0 },
  ],
  "cm2|Angles": [
    { q: "Un angle droit mesure…", r: ["45°", "90°", "180°", "60°"], ok: 1 },
    { q: "La moitié d'un angle droit mesure…", r: ["30°", "45°", "90°", "180°"], ok: 1 },
    { q: "Un angle de 120° est…", r: ["aigu", "droit", "obtus", "nul"], ok: 2 },
    { q: "Un angle de 30° est…", r: ["aigu", "droit", "obtus", "plat"], ok: 0 },
    { q: "Deux angles droits côte à côte font…", r: ["90°", "180°", "45°", "360°"], ok: 1 },
    { q: "Pour construire la moitié d'un angle, on peut…", r: ["le plier en deux", "le peser", "le colorier", "le mesurer à la règle"], ok: 0 },
  ],
  "cm2|Heures et durées": [
    { q: "1 min = … s", r: ["60", "100", "24", "30"], ok: 0 },
    { q: "2 min 30 s = … s", r: ["230", "150", "120", "180"], ok: 1 },
    { q: "De 14 h 50 à 15 h 25, il s'écoule…", r: ["35 min", "25 min", "75 min", "45 min"], ok: 0 },
    { q: "90 min = …", r: ["1 h 30 min", "1 h 50 min", "9 h", "1 h 9 min"], ok: 0 },
    { q: "Un trajet de 2 h 45 min part à 8 h 30. Arrivée à…", r: ["11 h 15", "10 h 75", "11 h 25", "10 h 15"], ok: 0 },
    { q: "Un quart d'heure = … min", r: ["15", "25", "4", "45"], ok: 0 },
  ],
  "cm2|Procédures de calcul mental": [
    { q: "3,7 × 10 = …", r: ["3,70", "37", "370", "0,37"], ok: 1 },
    { q: "52 ÷ 4 = …", r: ["13", "12", "14", "26"], ok: 0 },
    { q: "2,4 + 3,5 = …", r: ["5,9", "5,8", "6,9", "59"], ok: 0 },
    { q: "La moitié de 7 est…", r: ["3", "3,5", "4", "3,7"], ok: 1 },
    { q: "1,2 × 5 = …", r: ["6", "5,2", "60", "0,6"], ok: 0 },
    { q: "456 + 99 = …", r: ["555", "545", "556", "565"], ok: 0 },
  ],
  "cm2|Solides et repérage dans l'espace": [
    { q: "Combien de sommets a un cube ?", r: ["6", "8", "12", "4"], ok: 1 },
    { q: "Les faces d'un pavé droit sont des…", r: ["triangles", "rectangles", "disques", "pentagones"], ok: 1 },
    { q: "Combien de faces a un prisme droit à base triangulaire ?", r: ["3", "5", "6", "9"], ok: 1 },
    { q: "Combien de patrons différents a le cube ?", r: ["6", "8", "11", "24"], ok: 2 },
    { q: "Deux étages de 4 cubes : combien de cubes en tout ?", r: ["6", "8", "16", "4"], ok: 1 },
    { q: "Quel solide a une face plane en forme de disque et une pointe ?", r: ["le cylindre", "le cône", "la boule", "la pyramide"], ok: 1 },
  ],
  "cm2|Proportionnalité": [
    { q: "3 baguettes coûtent 2,70 €. 6 baguettes coûtent…", r: ["5,40 €", "5,70 €", "8,10 €", "3,60 €"], ok: 0 },
    { q: "5 kg coûtent 15 €. 1 kg coûte…", r: ["3 €", "5 €", "10 €", "75 €"], ok: 0 },
    { q: "Une recette pour 6 personnes : 300 g. Pour 2 personnes ?", r: ["100 g", "150 g", "200 g", "600 g"], ok: 0 },
    { q: "En 2 h, on parcourt 120 km. En 5 h, à la même vitesse ?", r: ["240 km", "300 km", "600 km", "125 km"], ok: 1 },
    { q: "Le prix de timbres identiques est-il proportionnel à leur nombre ?", r: ["Oui", "Non"], ok: 0 },
    { q: "4 cahiers coûtent 6 € et 6 cahiers 9 €. 10 cahiers coûtent…", r: ["15 €", "12 €", "60 €", "24 €"], ok: 0 },
  ],
  "cm2|Algèbre": [
    { q: "178 − … = 6 × 8", r: ["130", "48", "226", "120"], ok: 0 },
    { q: "Si n = 4, combien vaut n × 12 + 5 ?", r: ["53", "68", "21", "48"], ok: 0 },
    { q: "3, 7, 11, 15… Le nombre suivant est…", r: ["18", "19", "20", "17"], ok: 1 },
    { q: "■ + ■ = 18. ■ vaut…", r: ["8", "9", "36", "18"], ok: 1 },
    { q: "Programme : × 3, puis − 4. Avec 6, on obtient…", r: ["14", "10", "22", "5"], ok: 0 },
    { q: "2 stylos et 1 cahier coûtent 7 €. Le cahier coûte 3 €. Un stylo coûte…", r: ["2 €", "4 €", "1 €", "3 €"], ok: 0 },
  ],
  "cm2|Pensée informatique": [
    { q: "Le robot regarde vers le nord. Il tourne à droite : il regarde vers…", r: ["l'est", "l'ouest", "le sud", "le nord"], ok: 0 },
    { q: "Le robot tourne 2 fois à gauche. Il a fait…", r: ["un demi-tour", "un quart de tour", "un tour complet", "rien"], ok: 0 },
    { q: "« Répéter 4 fois : avancer de 3, tourner à droite » dessine…", r: ["un carré", "un triangle", "un cercle", "une ligne"], ok: 0 },
    { q: "Programme : × 2, puis + 1, puis × 10. Avec 3, on obtient…", r: ["70", "61", "37", "90"], ok: 0 },
    { q: "Dans un tableur, une case s'appelle…", r: ["une cellule", "une boucle", "un bloc", "un robot"], ok: 0 },
    { q: "Une boucle sert à…", r: ["répéter des instructions", "effacer le programme", "tourner le robot", "tout arrêter"], ok: 0 },
  ],
};
// Les questions déclarées dans le chapitre lui-même (cm1Chapitre › flash) restent prioritaires.
Object.keys(F).forEach(k => { if(!CM_FLASH[k]) CM_FLASH[k] = F[k]; });
})();
